version: '3'

volumes:
  wheelbuild:
    driver: local
  pipcache:
    driver: local

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - pipcache:/cache
      - wheelbuild:/build
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports

  pipcache:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - /tmp/cache:/cache
      - /wheelbuild
    entrypoint: "true"

  builder:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - wheelbuild:/build
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build", "."]

  agent:
    image: jeremyxu666/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]

  db:
    image: mysql:8.0
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
